name: Check Hostname

on:
  push

jobs:
  check-hostname:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run check-hostname.py
        run: python check-hostname.py

      - name: Run hostname check script-old
        run: |
          echo "Hostname: $env:COMPUTERNAME"
          echo "Fully Qualified Domain Name: $([System.Net.Dns]::GetHostEntry([System.Net.Dns]::GetHostName()).HostName)"
          echo "Pinging localhost..."
          ping -n 1 localhost
          echo "Pinging hostname..."
          ping -n 1 $env:COMPUTERNAME
          echo "Pinging FQDN..."
          ping -n 1 [System.Net.Dns]::GetHostEntry([System.Net.Dns]::GetHostName()).HostName
        shell: pwsh
        if: runner.os == 'Windows' && always()

      - name: Run hostname check script (PowerShell)
        run: |
          echo "Hostname: $env:COMPUTERNAME"
          $fqdn = [System.Net.Dns]::GetHostEntry([System.Net.Dns]::GetHostName()).HostName
          echo "Fully Qualified Domain Name: $fqdn"
          echo "Pinging localhost..."
          ping -n 1 localhost
          echo "Pinging hostname..."
          ping -n 1 $env:COMPUTERNAME
          echo "Pinging FQDN..."
          ping -n 1 $fqdn
        shell: pwsh
        if: runner.os == 'Windows' && always()
